version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: licoreria_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-licoreria}
    ports:
      - "5432:5432"
    volumes:
      - ./docker-data/postgres:/var/lib/postgresql/data
    networks:
      - licoreria_net

  adminer:
    image: adminer
    container_name: licoreria_adminer
    restart: always
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    networks:
      - licoreria_net

networks:
  licoreria_net:
    driver: bridge
